<div id="messages"><div class="messages"><div class="message message-notice notice"><div><?php echo __('<b>TIP :</b> Use this module for update products images after import the products.'); ?></div></div></div></div>
<div class="download_image_info">
<p><?php echo __("This module is used for download products images from live URL and generate CSV according to our extension.") ?></p>
<p>&nbsp;</p>
<p><b><?php echo __("How to Use") ?> :-</b></p>
<ul>
	<li><?php echo __("1. Make your CSV file as per given") ?> <a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-magento-2-csv/download_images_sample.csv"><?php echo __("Sample CSV") ?></a> <?php echo __("file.") ?></li>
	<li><?php echo __("2. Upload file from 'Download Products Images' section. ")?></li>
	<li><?php echo __("3. Click on 'Download Images and Generate csv' button. ")?></li>
	<li><?php echo __("4. Your images are downloaded and store in <b>pub/media/import</b> folder and generate CSV file according to our extension and store in <b>var/import</b> folder.")?></li>
	<li><?php echo __("5. Now goto <b>MageBees -> Import Export Products -> Import Products -> Run Profile</b>. Select your generated CSV file and click on Validate & Import File Data Button.")?></li>
</ul>
</div>