<div class="docwrap">
	<div class="secone"><a href="https://www.magebees.com/media/mconnect_uploadfiles/u/s/user_guide_magebees_import_export_products_for_magento_2_extension_v1.3.2.pdf" target="_blank"><?php echo __("Documentation") ?></a></div>
	<div class="secone"><a href="https://www.magebees.com/media/mconnect_uploadfiles/i/m/import_export_product_sample_csv.zip" target="_blank"><?php echo __("Sample CSV Files") ?></a></div>
</div>