<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_GXpress
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */

/*Ced\GXpress\Block\Adminhtml\Order\ShipGXpressOrder $block*/

$orderData = $block->getModel();
$gxpresshelper = $block->getHelper('\GXpress');
$datahelper = $block->getHelper('\Data');
$mageOrderId = $this->getRequest()->getParam('order_id');
$orderObj = $block->getOrder();
$shipInfo = json_decode($orderData->getShipmentData(), true);
$dataInfo = json_decode($orderData->getOrderData(), true);
$id = $orderData->getId();


if ($orderData->getStatus() == 'shipped') { ?>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <div class="admin__page-section-item-title">
                <span class="title">gxpress Order Details</span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th>Order Placed on gxpress</th>
                        <td><?php echo "<prE>";
                            echo date('l, F jS Y', strtotime($orderData->getOrderPlaceDate())); ?></td>
                    </tr>
                    <tr>
                        <th>Shipping Carrier</th>
                        <td>
                            <?php
                            $carrier = isset($shipInfo['shipments']) ? $shipInfo['shipments'][0]["carrier"] : $shipInfo[0]["carrier"];
                            echo $carrier;
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Tracking Number</th>
                        <td>
                            <?php
                            $tracking = isset($shipInfo['shipments']) ? $shipInfo['shipments'][0]["shipment_tracking_number"] : $shipInfo[0]["trackingId"];
                            echo $tracking;
                            ?>
                        </td>
                    </tr>
                    <!--<tr>
                        <th>gxpress Delivery Date</th>
                        <td>
                            <?php
                    /*                            $date = isset($shipInfo['shipments']) ?
                                                    date('l, F jS Y',strtotime($shipInfo['shipments'][0]["response_shipment_date"])) :
                                                    date('l, F jS Y',strtotime($shipInfo[0]["creationDate"]));
                                                echo $date;
                                                */ ?>
                        </td>
                    </tr>-->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="admin__page-section-title">
        <span class="title">Shipment Order Items</span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table" id="_prod_table">
            <thead>
            <tr class="headings">
                <th>Product sku</th>
                <th>Quantity ordered</th>
                <th>Quantity to Ship</th>
                <th>Quantity to Cancel</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($dataInfo['lineItems'] as $valdata) { ?>
                <tr>
                <td><strong><?php echo $valdata['product']['offerId'] ?></strong></td>
                <td><strong><?php echo $valdata['quantityOrdered'] ?></strong></td>
                <td><strong><?php echo $valdata['quantityShipped'] ?></strong></td>
                <td><strong><?php echo $valdata['quantityCanceled'] ?></strong></td>
                </tr><?php } ?>
            </tbody>
        </table>
    </div>
    <h3>Order Shipped Successfully</h3>
<?php } else if ($orderData->getStatus() == 'acknowledge'
    || $orderData->getStatus() == 'inProgress'
    || $orderData->getStatus() == 'pendingShipment'
) { ?>
    <p>
        <input type="hidden" id="gxpressorderid" value="<?php echo $orderData->getGXpressOrderId() ?>" readonly>
        <input type="hidden" id="incrementid" value="<?php echo $block->getOrder()->getIncrementId() ?>">
        <input type="hidden" id="form_key" value="<?php echo $block->getFormKey(); ?>">
        <input type="hidden" id="magento_orderid" value="<?php echo $mageOrderId ?>">
    </p>

    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <div class="admin__page-section-item-title">
                <span class="title">gxpress Order Information</span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th>Order Placed on gxpress</th>
                        <td><?php echo date('l, F jS Y', strtotime($orderData->getOrderPlaceDate())); ?></td>
                    </tr>
                    <tr>
                        <th>Shipping Carrier</th>
                        <td>
                            <?php echo $dataInfo['lineItems'][0]['shippingDetails']['method']['carrier'] ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Tracking Number</th>
                        <td><input class="admin__control-text" type="text" id="tracking" value=""></td>
                    </tr>
                    <tr>
                        <th>gxpress Delivery Date</th>
                        <td><input class="admin__control-text input-text required-entry" type="text" id="ship_date"
                                   name="ship_date"/></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="admin__page-section-title">
        <span class="title">Shipment Order Items</span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table" id="_prod_table">
            <thead>
            <tr class="headings">
                <th>Product sku</th>
                <th>Quantity ordered</th>
                <th>Quantity to Ship</th>
                <th>Quantity to Cancel</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $k = 0;
            if (isset($dataInfo['lineItems'][0])) {
                $checkData = $dataInfo['lineItems'];
            } /*else {
                $checkData = $dataInfo['lineItems'];
            }*/
            foreach ($checkData as $valdata) {
                $sku = isset($valdata['product']['offerId']) ? $valdata['product']['offerId'] : $valdata['product']['itemGroupId'];
                $cancel_qty = 0;
                $avail_qty = $valdata['quantityOrdered'];
                if ($avail_qty > 0) { ?>
                    <tr>
                    <td><input type="hidden" id="sku_<?php echo $k; ?>" value="<?php echo $sku ?>">
                        <strong><?php echo $sku ?></strong>
                    </td>
                    <td><input type="hidden" id="qty_<?php echo $k; ?>" value="<?php echo $avail_qty ?>">
                        <strong><?php echo $avail_qty ?></strong>
                    </td>
                    <td><input type="text" id="ship_<?php echo $k; ?>" class="admin__control-text"
                               value="<?php echo $avail_qty; ?>">
                    </td>
                    <td><input class="admin__control-text" type="text" id="can_<?php echo $k; ?>"
                               value="<?php echo $cancel_qty; ?>">
                    </td>
                    </tr><?php }
                $k++;
            }
            ?>
            </tbody>
        </table>
    </div>
    <br/>
    <button class="primary" id="button1" onclick="CallShipment();">Submit
        Shipment
    </button><br/>

    <script>
        require([
            "jquery",
            "mage/calendar"
        ], function ($) {
            $('#ship_date').calendar({
                showsTime: false,
                hideIfNoPrevNext: true,
                buttonText: "<?php echo __('Select Date') ?>",
                dateFormat: "yy-mm-dd",
                minDate: new Date()
            });
        });
    </script>
    <script>

        function CallShipment() {
            var key = document.getElementById('form_key').value;
            var incrementid = document.getElementById('incrementid').value;
            var magento_orderid = document.getElementById('magento_orderid').value;
            var gxpressorderid = document.getElementById('gxpressorderid').value;
            var carrier = document.getElementById('carrier').value;
            var tracking = document.getElementById('tracking').value;
            var ship_todate = document.getElementById('ship_date').value;

            var outterArray = [];
            var lengthval = <?php echo $k; ?>;
            var gxpressid = <?php echo $id; ?>;

            for (var i = 0; i < lengthval; i++) {
                if (document.getElementById('sku_' + i)) {
                    product_sku = document.getElementById('sku_' + i).value;
                    requested_quantity = document.getElementById('qty_' + i).value;
                    cancel_quantity = document.getElementById('can_' + i).value;
                    ship_quantity = document.getElementById('ship_' + i).value;

                    if ((cancel_quantity != requested_quantity) && (requested_quantity != ship_quantity)) {
                        alert("please either ship complete ship or cancel this order");
                    }
                    if ((cancel_quantity == requested_quantity) && (requested_quantity == ship_quantity)) {
                        alert("please either ship complete ship or cancel this order");
                    }

                    if (ship_quantity < 1) {
                        var check = false;
                    } else {
                        var check = true;
                    }
                    var product_data = {
                        sku: product_sku, req_qty: requested_quantity, ship_qty: ship_quantity,
                        cancel_quantity: cancel_quantity
                    };

                    outterArray.push(product_data);
                }
            }
            if (check) {
                if (carrier == "") {
                    alert("Please enter Shipping carrier");
                    return;
                }
                if (tracking == "") {
                    alert("Please Enter Tracking Number");
                    return;
                }
                if (ship_todate == "") {
                    alert("Please enter delivery date");
                    return;
                }
            }

            new Ajax.Request("<?php echo $this->getUrl('gxpress/order/ship') ?>", {
                method: 'Post',
                parameters: {
                    "id": gxpressid,
                    "gxpressorderid": gxpressorderid,
                    "items": JSON.stringify(outterArray),
                    "carrier": carrier,
                    "incrementid": incrementid,
                    "magento_orderid": magento_orderid,
                    "tracking": tracking,
                    "ship_todate": ship_todate
                },

                onComplete: function (transport) {
                    if (transport.responseText == "Success") {
                        try {
                            window.location.href = "";
                        } catch (err) {
                            alert(transport.responseText);
                        }
                    } else {
                        alert(transport.responseText);
                    }
                }
            });

        }

    </script>
<?php } ?>
<style>
    #item > tr > td > input, select {
        width: 100% !important;
    }
</style>
